version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  ticket-service:
    build:
      context: .
      dockerfile: Dockerfile.ticket-service
    ports:
      - "4000:4000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - ticket-service

volumes:
  mongo-data:
