version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: assane764/frontend-image:${BUILD_NUMBER:-latest}-frontend
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL=http://frontend:3000
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: assane764/backend-image:${BUILD_NUMBER:-latest}-backend
    ports:
      - "4000:4000"
    environment:
      - BACKEND_URL=http://backend:4000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  