# fichier : infrastructure/docker-compose_test.yml
version: '3.8'  
services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: tickets-backend:latest
    ports:
      - "4000:4000"
      - "8000:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: tickets-frontend:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
