# fichier : infrastructure/docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ticketsdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: tickets-backend:latest
    command: node server.js # override du CMD pour lancer server.js
    depends_on:
      db:
        condition: service_healthy # Attend que Postgres soit UP
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: ticketsdb
    ports:
      - "5000:5000"
    volumes:
      - ../backend:/app

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: tickets-frontend:latest
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    ports:
      - "3000:3000"

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
