pipeline {
    agent any  // Choisit automatiquement un agent disponible

    environment {
        // Tu peux définir des variables d'environnement ici si besoin
        DOCKER_IMAGE = 'mon-image-devops'
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/GemimaOndele/Projet-DEVOPS.git', branch: 'main'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Run Container') {
            steps {
                script {
                    sh 'docker run -d --name mon-conteneur-devops $DOCKER_IMAGE'
                }
            }
        }
    }

    post {
        always {
            echo 'Nettoyage Docker...'
            sh 'docker container prune -f'
            sh 'docker image prune -f'
        }
    }
}
